apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gv5d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-gv5d@sha256:f6dfcd0f506cbffef6384642bbece334e69e63aedc98eac77463bf802ac93dad
        name: my-nodejs
        resources: {}
status: {}
